### ISSUE TITLE
yt-dlp-compose.exe  dialog  Failed to launch JVM   

### ISSUE THREAD

**Issue by aryanchoudharypro** [StefanLobbenmeier/yt-dlp-compose#73]

**Comment by StefanLobbenmeier** [comment]
Which OS version are you on? I remember someone else having this issue with windows 7

**Comment by aryanchoudharypro** [comment]
Windows 11 insider preview dev 26100.1

**Comment by aryanchoudharypro** [comment]
Yes thanks, also I wanted to ask if you have tested the program with the screen reader on windows as I am a blind windows user myself

**Comment by StefanLobbenmeier** [comment]
Have not tried with screen reader on windows, just tried with screen reader on macOS - buttons all have nice descriptions and are interactable, but text fields are missing descriptions and somehow labels are never read out, not sure why / what I need to do to support that

**Comment by StefanLobbenmeier** [comment]
So with the app accessibility inspector I can see all the labels in the app, so it seems to be mostly an issue with me not knowing how to use a screen reader to read out the labels 😄 

On windows accessibility is supported in principle, but requires a command to be executed, see https://github.com/JetBrains/compose-multiplatform/issues/4779. I hope that this will be done automatically when the linked issue is closed.

**Comment by aryanchoudharypro** [comment]
and this is what i get when i run the jar file with the cli. [main] INFO Main - /
Exception in thread "main" java.lang.ExceptionInInitializerError
        at androidx.compose.ui.scene.skia.WindowSkiaLayerComponent.<init>(WindowSkiaLayerComponent.desktop.kt:44)
        at androidx.compose.ui.scene.ComposeContainer.createSkiaLayerComponent(ComposeContainer.desktop.kt:341)
        at androidx.compose.ui.scene.ComposeContainer.access$createSkiaLayerComponent(ComposeContainer.desktop.kt:82)
        at androidx.compose.ui.scene.ComposeContainer$mediator$2.invoke(ComposeContainer.desktop.kt:138)
        at androidx.compose.ui.scene.ComposeContainer$mediator$2.invoke(ComposeContainer.desktop.kt:138)
        at androidx.compose.ui.scene.ComposeSceneMediator$skiaLayerComponent$2.invoke(ComposeSceneMediator.desktop.kt:132)
        at androidx.compose.ui.scene.ComposeSceneMediator$skiaLayerComponent$2.invoke(ComposeSceneMediator.desktop.kt:132)
        at kotlin.SynchronizedLazyImpl.getValue(LazyJVM.kt:74)
        at androidx.compose.ui.scene.ComposeSceneMediator.getSkiaLayerComponent(ComposeSceneMediator.desktop.kt:132)
        at androidx.compose.ui.scene.ComposeSceneMediator.<init>(ComposeSceneMediator.desktop.kt:133)
        at androidx.compose.ui.scene.ComposeSceneMediator.<init>(ComposeSceneMediator.desktop.kt:102)
        at androidx.compose.ui.scene.ComposeContainer.<init>(ComposeContainer.desktop.kt:127)
        at androidx.compose.ui.scene.ComposeContainer.<init>(ComposeContainer.desktop.kt:82)
        at androidx.compose.ui.awt.ComposeWindowPanel.<init>(ComposeWindowPanel.desktop.kt:52)
        at androidx.compose.ui.awt.ComposeWindow.<init>(ComposeWindow.desktop.kt:65)
        at androidx.compose.ui.awt.ComposeWindow.<init>(ComposeWindow.desktop.kt:63)
        at androidx.compose.ui.window.Window_desktopKt$Window$3.invoke(Window.desktop.kt:182)
        at androidx.compose.ui.window.Window_desktopKt$Window$3.invoke(Window.desktop.kt:176)
        at androidx.compose.ui.window.Window_desktopKt$Window$10.invoke(Window.desktop.kt:409)
        at androidx.compose.ui.window.Window_desktopKt$Window$10.invoke(Window.desktop.kt:406)
        at androidx.compose.ui.window.AwtWindow_desktopKt$AwtWindow$2.invoke(AwtWindow.desktop.kt:70)
        at androidx.compose.ui.window.AwtWindow_desktopKt$AwtWindow$2.invoke(AwtWindow.desktop.kt:69)
        at androidx.compose.runtime.DisposableEffectImpl.onRemembered(Effects.kt:82)
        at androidx.compose.runtime.CompositionImpl$RememberEventDispatcher.dispatchRememberObservers(Composition.kt:1295)
        at androidx.compose.runtime.CompositionImpl.applyChangesInLocked(Composition.kt:984)
        at androidx.compose.runtime.CompositionImpl.applyChanges(Composition.kt:1005)
        at androidx.compose.runtime.Recomposer.composeInitial$runtime(Recomposer.kt:1099)
        at androidx.compose.runtime.CompositionImpl.composeInitial(Composition.kt:633)
        at androidx.compose.runtime.CompositionImpl.setContent(Composition.kt:619)
        at androidx.compose.ui.window.Application_desktopKt$awaitApplication$2$1$2.invokeSuspend(Application.desktop.kt:221)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:104)
        at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:318)
        at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:773)
        at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:720)
        at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:714)
        at java.base/java.security.AccessController.doPrivileged(AccessController.java:400)
        at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:87)
        at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:742)
        at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
        at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
        at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
        at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
        at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
        at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
Caused by: org.jetbrains.skiko.LibraryLoadException: Cannot find skiko-windows-x64.dll.sha256, proper native dependency missing.
        at org.jetbrains.skiko.Library.findAndLoad(Library.kt:103)
        at org.jetbrains.skiko.Library.load(Library.kt:56)
        at org.jetbrains.skiko.SkiaLayer.<clinit>(SkiaLayer.awt.kt:32)
        ... 45 more

**Comment by StefanLobbenmeier** [comment]
Are you by chance on arm64 windows?

> org.jetbrains.skiko.LibraryLoadException: Cannot find skiko-windows-x64.dll.sha256, proper native dependency missing

**Comment by aryanchoudharypro** [comment]
no

**Comment by aryanchoudharypro** [comment]
do i have to install anything elce besides yt-dlp-compose?

**Comment by StefanLobbenmeier** [comment]
No it should work out of the box.

just to confirm, you downloaded the jar file from the release and used your own Java runtime to execute it?

**Comment by aryanchoudharypro** [comment]
i tryed the exe first, and then the jar file

**Comment by StefanLobbenmeier** [comment]
Alright, I will verify that it runs on my windows machine

**Comment by aryanchoudharypro** [comment]
i'll also try it on windows 10 to sea if it works ,

**Comment by StefanLobbenmeier** [comment]
Ok so the exe works for me on windows 11 23H2, with the .jar file I have the same issue. It might be that the Java runtime needs some library that is not included by default on windows

**Comment by StefanLobbenmeier** [comment]
I think it’s this: https://stackoverflow.com/a/75099995

**Comment by StefanLobbenmeier** [comment]
The new .jar here should include the necessary files for windows: https://github.com/StefanLobbenmeier/yt-dlp-compose/releases/tag/SNAPSHOT-35

**Comment by aryanchoudharypro** [comment]
ok, so the exe stil doesn't work nither does the jar file. i get this output in the cmd window.
Microsoft Windows [Version 10.0.26100.1]
(c) Microsoft Corporation. All rights reserved.

C:\Users\aryan\downloads>java -jar yt-dlp-compose.jar
[main] INFO Main - /
[AWT-EventQueue-0] WARN de.lobbenmeier.stefan.settings.business.SettingsViewModel - Settings file C:\Users\aryan\AppData\Roaming\yt-dlp-compose\config\settings.json not found for Platform(name=Name: Windows 11, Version: 10.0, Architecture: amd64, ytDlpName=windows, ffmpegPlatform=windows64, needsExecutableBit=false)
[DefaultDispatcher-worker-4] INFO de.lobbenmeier.stefan.updater.business.KtorFileDownloadWithProgress - Starting download to C:\Users\aryan\AppData\Roaming\yt-dlp-compose\data\binaries\ffbinaries\6.1\ffmpeg from https://github.com/ffbinaries/ffbinaries-prebuilt/releases/download/v6.1/ffmpeg-6.1-win-64.zip
[DefaultDispatcher-worker-10] INFO de.lobbenmeier.stefan.updater.business.KtorFileDownloadWithProgress - Target file C:\Users\aryan\AppData\Roaming\yt-dlp-compose\data\binaries\yt-dlp\yt-dlp-nightly-builds\2024.08.21.232751 has already been downloaded
Exception in thread "AWT-EventQueue-0" java.lang.IllegalArgumentException: current must not be NaN
        at androidx.compose.ui.semantics.ProgressBarRangeInfo.<init>(SemanticsProperties.kt:575)
        at androidx.compose.foundation.ProgressSemanticsKt$progressSemantics$1.invoke(ProgressSemantics.kt:53)
        at androidx.compose.foundation.ProgressSemanticsKt$progressSemantics$1.invoke(ProgressSemantics.kt:51)
        at androidx.compose.ui.semantics.CoreSemanticsModifierNode.applySemantics(SemanticsModifier.kt:77)
        at androidx.compose.ui.node.LayoutNode$collapsedSemantics$1.invoke(LayoutNode.kt:430)
        at androidx.compose.ui.node.LayoutNode$collapsedSemantics$1.invoke(LayoutNode.kt:421)
        at androidx.compose.runtime.snapshots.Snapshot$Companion.observe(Snapshot.kt:2304)
        at androidx.compose.runtime.snapshots.SnapshotStateObserver$ObservedScopeMap.observe(SnapshotStateObserver.kt:504)
        at androidx.compose.runtime.snapshots.SnapshotStateObserver.observeReads(SnapshotStateObserver.kt:260)
        at androidx.compose.ui.node.OwnerSnapshotObserver.observeReads$ui(OwnerSnapshotObserver.kt:133)
        at androidx.compose.ui.node.OwnerSnapshotObserver.observeSemanticsReads$ui(OwnerSnapshotObserver.kt:121)
        at androidx.compose.ui.node.LayoutNode.getCollapsedSemantics$ui(LayoutNode.kt:421)
        at androidx.compose.ui.semantics.SemanticsNodeKt.SemanticsNode(SemanticsNode.kt:48)
        at androidx.compose.ui.semantics.SemanticsNode.fillOneLayerOfSemanticsWrappers(SemanticsNode.kt:268)
        at androidx.compose.ui.semantics.SemanticsNode.fillOneLayerOfSemanticsWrappers(SemanticsNode.kt:270)
        at androidx.compose.ui.semantics.SemanticsNode.fillOneLayerOfSemanticsWrappers(SemanticsNode.kt:270)
        at androidx.compose.ui.semantics.SemanticsNode.fillOneLayerOfSemanticsWrappers(SemanticsNode.kt:270)
        at androidx.compose.ui.semantics.SemanticsNode.fillOneLayerOfSemanticsWrappers(SemanticsNode.kt:270)
        at androidx.compose.ui.semantics.SemanticsNode.unmergedChildren$ui(SemanticsNode.kt:248)
        at androidx.compose.ui.semantics.SemanticsNode.getChildren(SemanticsNode.kt:327)
        at androidx.compose.ui.semantics.SemanticsNode.getReplacedChildren$ui(SemanticsNode.kt:298)
        at androidx.compose.ui.platform.a11y.AccessibilityController.syncNodes(AccessibilityController.kt:256)
        at androidx.compose.ui.platform.a11y.AccessibilityController.access$syncNodes(AccessibilityController.kt:52)
        at androidx.compose.ui.platform.a11y.AccessibilityController$launchSyncLoop$1$1.invokeSuspend(AccessibilityController.kt:219)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:104)
        at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:318)
        at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:773)
        at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:720)
        at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:714)
        at java.base/java.security.AccessController.doPrivileged(AccessController.java:400)
        at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:87)
        at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:742)
        at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
        at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
        at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
        at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
        at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
        at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
        Suppressed: kotlinx.coroutines.internal.DiagnosticCoroutineContextException: [androidx.compose.ui.scene.ComposeContainer$DesktopCoroutineExceptionHandler@58eb29b5, StandaloneCoroutine{Cancelling}@444e2f73, SwingDispatcher@39409805]
Exception in thread "DefaultDispatcher-worker-11" io.ktor.client.plugins.HttpRequestTimeoutException: Request timeout has expired [url=https://objects.githubusercontent.com/github-production-release-asset-2e65be/73596626/5fc61863-9974-4103-9b0e-7d6259f18c84?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=releaseassetproduction%2F20240826%2Fus-east-1%2Fs3%2Faws4_request&X-Amz-Date=20240826T025420Z&X-Amz-Expires=300&X-Amz-Signature=17fe7defed639a359c6122790f2a5c6ea9a6aded08d3b0d6b2b4705f313e6345&X-Amz-SignedHeaders=host&actor_id=0&key_id=0&repo_id=73596626&response-content-disposition=attachment%3B%20filename%3Dffmpeg-6.1-win-64.zip&response-content-type=application%2Foctet-stream, request_timeout=unknown ms]
        at io.ktor.client.engine.cio.EndpointKt$setupTimeout$timeoutJob$1.invokeSuspend(Endpoint.kt:307)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:104)
        at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:585)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:802)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:706)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:693)
        Suppressed: kotlinx.coroutines.internal.DiagnosticCoroutineContextException: [StandaloneCoroutine{Cancelling}@30f345d6, Dispatchers.IO]
Exception in thread "Thread-1" java.lang.RuntimeException: java.lang.NullPointerException: getGraphicsConfiguration(...) must not be null
        at jdk.accessibility/com.sun.java.accessibility.internal.AccessBridge$InvocationUtils.invokeAndWait(AccessBridge.java:7352)
        at jdk.accessibility/com.sun.java.accessibility.internal.AccessBridge$InvocationUtils.invokeAndWait(AccessBridge.java:7327)
        at jdk.accessibility/com.sun.java.accessibility.internal.AccessBridge.getAccessibleBoundsOnScreenFromContext(AccessBridge.java:1662)
        at jdk.accessibility/com.sun.java.accessibility.internal.AccessBridge.getAccessibleXcoordFromContext(AccessBridge.java:1693)
        at jdk.accessibility/com.sun.java.accessibility.internal.AccessBridge.runDLL(Native Method)
        at jdk.accessibility/com.sun.java.accessibility.internal.AccessBridge$dllRunner.run(AccessBridge.java:251)
        at java.base/java.lang.Thread.run(Thread.java:1583)
Caused by: java.lang.NullPointerException: getGraphicsConfiguration(...) must not be null
        at androidx.compose.ui.window.LayoutConfiguration_desktopKt.getDensity(LayoutConfiguration.desktop.kt:45)
        at androidx.compose.ui.scene.ComposeSceneMediator$DesktopPlatformComponent.getDensity(ComposeSceneMediator.desktop.kt:686)
        at androidx.compose.ui.platform.a11y.ComposeAccessible$ComposeAccessibleComponent.getDensity(ComposeAccessible.kt:169)
        at androidx.compose.ui.platform.a11y.ComposeAccessible$ComposeAccessibleComponent.toAwtRectangle(ComposeAccessible.kt:231)
        at androidx.compose.ui.platform.a11y.ComposeAccessible$ComposeAccessibleComponent.getBounds(ComposeAccessible.kt:356)
        at jdk.accessibility/com.sun.java.accessibility.internal.AccessBridge$71.call(AccessBridge.java:1667)
        at jdk.accessibility/com.sun.java.accessibility.internal.AccessBridge$71.call(AccessBridge.java:1662)
        at jdk.accessibility/com.sun.java.accessibility.internal.AccessBridge$InvocationUtils$CallableWrapper.run(AccessBridge.java:7408)
        at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:308)
        at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:773)
        at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:720)
        at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:714)
        at java.base/java.security.AccessController.doPrivileged(AccessController.java:400)
        at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:87)
        at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:742)
        at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
        at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
        at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
        at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
        at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
        at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)

 and a window with some text. 
current must not be NaN

**Comment by aryanchoudharypro** [comment]
it opens now after disableing and reenabling the java access bridg, but now nvda doesn't read things properly

**Comment by StefanLobbenmeier** [comment]
I see, you might be running into this issue then: 
https://github.com/JetBrains/compose-multiplatform/blob/master/tutorials/Accessibility/Windows.md#nvda-workaround

Ironically the workaround is described with screenshots, but here is the transcription:
1. nvda 2021.3.1 Properties
2. Tab "Compatibility"
3. Change high DPI settings
4. Override high DPI scaling behaviour. Scaling performed by: Application

**Comment by aryanchoudharypro** [comment]
It still doesn't work, and other thing I forgot to mention is that it
speaks the window title as untitled

**Comment by aryanchoudharypro** [comment]
ok can you tell me how to build it, maybe then it will work?

**Comment by aryanchoudharypro** [comment]
also, i've tested on a few laptops running windows 11 23h2 / 24h2 and it doesn't work on them.

**Comment by StefanLobbenmeier** [comment]
> ok can you tell me how to build it, maybe then it will work?

You can clone the repository and should see the exact command the build uses here:  https://github.com/StefanLobbenmeier/yt-dlp-compose/blob/adb67970e7603866f0f8febc8fe5f96977096893/.github/workflows/release.yml#L38C14-L38C40       

`./gradlew nativeDistribution --info --build-cache`

But I can also see on my machine that it seems to have some issue with downloading ffmpeg on windows, not sure why.

**Comment by aryanchoudharypro** [comment]
i do have ffmpeg in my path

**Comment by aryanchoudharypro** [comment]
ok so i tryed the latest build and it still has this error. is there a  way i can give you more info so this can finally be fixed?

**Comment by ENTPRESTIGIOUS** [comment]
Same issue on Windows 11 Pro 23H2 

![Image](https://github.com/user-attachments/assets/3fb44c34-dc02-443c-a2a1-6fd2de1d989d)

**Comment by StefanLobbenmeier** [comment]
Not sure what changed, last time I googled this I couldn’t find anything, now I found two ideas for me to try:

https://stackoverflow.com/a/78636453

https://github.com/JetBrains/compose-multiplatform/issues/4233

**Comment by aryanchoudharypro** [comment]
i am here to test if any changes are made

**Comment by StefanLobbenmeier** [comment]
I just triggered a release that should have a better error message, lets see what that prints for you:
https://github.com/StefanLobbenmeier/yt-dlp-compose/releases/tag/3.0.46


I will also try the solution from stackoverflow that should fix the error, but please try the release above first so we know the exact module(s) that are missing.

**Comment by StefanLobbenmeier** [comment]
If the hunch from stackoverflow is correct one of these should fix the error (released on a separate repo to not spam linux and mac users with that release), please try them after posting the error message from the other release:
- https://github.com/StefanLobbenmeier/yt-dlp-compose-test-CI-changes/releases/tag/3.0.12
- https://github.com/StefanLobbenmeier/yt-dlp-compose-test-CI-changes/releases/tag/3.0.13

**Comment by aryanchoudharypro** [comment]
ok so in 3.0.12, it shows a new error that is also there when running the jar file. its current must not be NaN
in the jar file, it prints this error from the cmd. 
[AWT-EventQueue-0] WARN de.lobbenmeier.stefan.settings.business.SettingsViewModel - Settings file C:\Users\aryan\AppData\Roaming\yt-dlp-compose\config\settings.json not found for Platform(name=Name: Windows 11, Version: 10.0, Architecture: amd64, ytDlpName=windows, ffmpegPlatform=windows64, needsExecutableBit=false, pathDelimiter=;, extraPaths=[])           
[AWT-EventQueue-0] INFO de.lobbenmeier.stefan.version.CheckForAppUpdate - Checking for app update                       
[DefaultDispatcher-worker-11] INFO de.lobbenmeier.stefan.updater.business.KtorFileDownloadWithProgress - Starting download to C:\Users\aryan\AppData\Roaming\yt-dlp-compose\data\binaries\ffbinaries\6.1\ffmpeg from https://github.com/ffbinaries/ffbinaries-prebuilt/releases/download/v6.1/ffmpeg-6.1-win-64.zip                                                     
[DefaultDispatcher-worker-2] INFO de.lobbenmeier.stefan.updater.business.KtorFileDownloadWithProgress - Starting download to C:\Users\aryan\AppData\Roaming\yt-dlp-compose\data\binaries\yt-dlp\yt-dlp\2025.02.19 from https://github.com/yt-dlp/yt-dlp/releases/download/2025.02.19/yt-dlp.exe                                                                         
Exception in thread "AWT-EventQueue-0" java.lang.IllegalArgumentException: current must not be NaN                      
        at androidx.compose.ui.semantics.ProgressBarRangeInfo.<init>(SemanticsProperties.kt:629)                        
        at androidx.compose.foundation.ProgressSemanticsKt$progressSemantics$1.invoke(ProgressSemantics.kt:53)          
        at androidx.compose.foundation.ProgressSemanticsKt$progressSemantics$1.invoke(ProgressSemantics.kt:51)          
        at androidx.compose.ui.semantics.CoreSemanticsModifierNode.applySemantics(SemanticsModifier.kt:77)              
        at androidx.compose.ui.node.LayoutNode$collapsedSemantics$1.invoke(LayoutNode.kt:442)                           
        at androidx.compose.ui.node.LayoutNode$collapsedSemantics$1.invoke(LayoutNode.kt:433)                           
        at androidx.compose.runtime.snapshots.Snapshot$Companion.observe(Snapshot.kt:2442)                              
        at androidx.compose.runtime.snapshots.SnapshotStateObserver$ObservedScopeMap.observe(SnapshotStateObserver.kt:505)                                                                                                                      
        at androidx.compose.runtime.snapshots.SnapshotStateObserver.observeReads(SnapshotStateObserver.kt:261)          
        at androidx.compose.ui.node.OwnerSnapshotObserver.observeReads$ui(OwnerSnapshotObserver.kt:133)                 
        at androidx.compose.ui.node.OwnerSnapshotObserver.observeSemanticsReads$ui(OwnerSnapshotObserver.kt:121)        
        at androidx.compose.ui.node.LayoutNode.getCollapsedSemantics$ui(LayoutNode.kt:433)                              
        at androidx.compose.ui.semantics.SemanticsNodeKt.SemanticsNode(SemanticsNode.kt:49)                             
        at androidx.compose.ui.semantics.SemanticsNode.fillOneLayerOfSemanticsWrappers(SemanticsNode.kt:278)            
        at androidx.compose.ui.semantics.SemanticsNode.fillOneLayerOfSemanticsWrappers(SemanticsNode.kt:280)            
        at androidx.compose.ui.semantics.SemanticsNode.fillOneLayerOfSemanticsWrappers(SemanticsNode.kt:280)            
        at androidx.compose.ui.semantics.SemanticsNode.fillOneLayerOfSemanticsWrappers(SemanticsNode.kt:280)            
        at androidx.compose.ui.semantics.SemanticsNode.fillOneLayerOfSemanticsWrappers(SemanticsNode.kt:280)            
        at androidx.compose.ui.semantics.SemanticsNode.unmergedChildren$ui(SemanticsNode.kt:257)                        
        at androidx.compose.ui.semantics.SemanticsNode.getChildren$ui(SemanticsNode.kt:338)                             
        at androidx.compose.ui.semantics.SemanticsNode.getChildren$ui$default(SemanticsNode.kt:322)                     
        at androidx.compose.ui.semantics.SemanticsNode.getReplacedChildren$ui(SemanticsNode.kt:305)                     
        at androidx.compose.ui.platform.a11y.AccessibilityController.syncNodes(AccessibilityController.kt:256)          
        at androidx.compose.ui.platform.a11y.AccessibilityController.access$syncNodes(AccessibilityController.kt:52)    
        at androidx.compose.ui.platform.a11y.AccessibilityController$launchSyncLoop$1$1.invokeSuspend(AccessibilityController.kt:219)                                                                                                           
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)                       
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:100)                                                 
        at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:318)                               
        at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:773)                                      
        at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:720)                                                  
        at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:714)                                                  
        at java.base/java.security.AccessController.doPrivileged(AccessController.java:400)                             
        at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:87)                                                                                                                    
        at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:742)                                          
        at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)               
        at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)                  
        at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)               
        at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)                           
        at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)                           
        at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)                                   
        Suppressed: kotlinx.coroutines.internal.DiagnosticCoroutineContextException: [androidx.compose.ui.scene.ComposeContainer$DesktopCoroutineExceptionHandler@883ca83, StandaloneCoroutine{Cancelling}@7392fcfd, SwingDispatcher@15e0df49]  
[

**Comment by aryanchoudharypro** [comment]
3.0.13 has the same error

**Comment by StefanLobbenmeier** [comment]
I see, and that error crashes the whole application? It looks to me like it’s an issue with the progress bar during the downloads of yt-dlp and ffmpeg, they don’t have a progress from the start, but I can set it to zero to make the issue go away for now.

Out of curiosity, 3.0.46 should have an error that jdk.accessibility is missing or something along those lines, can you confirm that?

**Comment by aryanchoudharypro** [comment]
yes, its this. Assistive Technology not found: com.sun.java.accessibility.AccessBridge

**Comment by aryanchoudharypro** [comment]
also cant it just check the path first to sea if yt-dlp and ffmpeg are already installed?

**Comment by StefanLobbenmeier** [comment]
> also cant it just check the path first to sea if yt-dlp and ffmpeg are already installed?

True, I wrote some logic to detect it but did not integrate it yet. For now it downloads it on the first start and then you can configure it to use the one in settings.

Background is that I originally had quite complicated logic for this and eventually I realized that this should not really be automatic logic that decides everything for you, but some kind of welcome wizard that guides you through those settings. But I did not get around to create that wizard yet 😄

**Comment by StefanLobbenmeier** [comment]
I figured out the NaN issue and created another release: https://github.com/StefanLobbenmeier/yt-dlp-compose/releases/tag/3.0.47

**Comment by aryanchoudharypro** [comment]
ok this runs. nvda doesn't work, but we can open a diffrent issue for it

**Comment by StefanLobbenmeier** [comment]
Created this follow up issue for the NVDA issue: https://github.com/StefanLobbenmeier/yt-dlp-compose/issues/156

**Comment by StefanLobbenmeier** [comment]
@ENTPRESTIGIOUS  could you also confirm the error is no longer there on latest version?

**Comment by ENTPRESTIGIOUS** [comment]
> [@ENTPRESTIGIOUS](https://github.com/ENTPRESTIGIOUS) could you also confirm the error is no longer there on latest version?

It opens now! Thanks!
